title: "DICT"
name: "Digital & Intelligence Convergence Team"
description: "数智融合创新研究团队"

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "air"   # 推荐 air / default / dark

locale: "en-US"

markdown: kramdown

# Header
masthead_title: "DICT"

# Footer
footer:
  links:
    - label: "GitHub"
      url: "https://github.com/UESTC-HZ"

# Navigation
nav: main