title: "DICT - Digital & Intelligence Convergence Team"
subtitle: "数智融合创新研究团队"
description: "We focus on AI systems, multimodal intelligence, and intelligent decision-making."

url: "https://uestc-hz.github.io"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-scholar

markdown: kramdown

collections:
  pages:
    output: true

scholar:
  style: apa
  locale: en

  source: ./_publications
  bibliography: papers.bib

  sort_by: year,month
  order: descending

  group_by: year

  replace_strings: true
  join_strings: true

  details_dir: publications
  details_layout: bibtex.html
  details_link: "details"

  bibliography_template: "{{reference}}"
